:: Set default build value only if not previously set
if not defined PROXSUITE_BUILD_TYPE (set PROXSUITE_BUILD_TYPE=Release)
if not defined PROXSUITE_BUILD_VECTORIZATION (set PROXSUITE_BUILD_VECTORIZATION=ON)
if not defined PROXSUITE_BUILD_PYTHON_INTERFACE (set PROXSUITE_BUILD_PYTHON_INTERFACE=OFF)
if not defined PROXSUITE_BUILD_TESTING (set PROXSUITE_BUILD_TESTING=ON)
if not defined PROXSUITE_BUILD_MAROS_MESZAROS_TESTS (set PROXSUITE_BUILD_MAROS_MESZAROS_TESTS=OFF)
