var searchData=
[
  ['rankrupdateloopimpl_0',['RankRUpdateLoopImpl',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RankRUpdateLoopImpl.html',1,'proxsuite::linalg::dense::_detail']]],
  ['rankrupdateloopimpl_3c_20false_20_3e_1',['RankRUpdateLoopImpl&lt; false &gt;',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RankRUpdateLoopImpl_3_01false_01_4.html',1,'proxsuite::linalg::dense::_detail']]],
  ['rankrupdateloopimpl_3c_20true_20_3e_2',['RankRUpdateLoopImpl&lt; true &gt;',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RankRUpdateLoopImpl_3_01true_01_4.html',1,'proxsuite::linalg::dense::_detail']]],
  ['rankupdateloadpmu_3',['RankUpdateLoadPMu',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RankUpdateLoadPMu.html',1,'proxsuite::linalg::dense::_detail']]],
  ['rankupdateloadw_4',['RankUpdateLoadW',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RankUpdateLoadW.html',1,'proxsuite::linalg::dense::_detail']]],
  ['rankupdatestorew_5',['RankUpdateStoreW',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RankUpdateStoreW.html',1,'proxsuite::linalg::dense::_detail']]],
  ['rankupdateupdatewandl_6',['RankUpdateUpdateWAndL',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RankUpdateUpdateWAndL.html',1,'proxsuite::linalg::dense::_detail']]],
  ['raw_7',['Raw',['../structproxsuite_1_1proxqp_1_1sparse_1_1detail_1_1AugmentedKkt_1_1Raw.html',1,'proxsuite::proxqp::sparse::detail::AugmentedKkt']]],
  ['rawvector_8',['RawVector',['../structproxsuite_1_1linalg_1_1veg_1_1vector_1_1RawVector.html',1,'proxsuite::linalg::veg::vector']]],
  ['rawvectormoveraii_9',['RawVectorMoveRaii',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1__vector_1_1RawVectorMoveRaii.html',1,'proxsuite::linalg::veg::_detail::_vector']]],
  ['ref_10',['ref',['../structproxsuite_1_1linalg_1_1veg_1_1nb_1_1ref.html',1,'proxsuite::linalg::veg::nb']]],
  ['ref_11',['Ref',['../structproxsuite_1_1linalg_1_1veg_1_1Ref.html',1,'proxsuite::linalg::veg']]],
  ['refbase_12',['RefBase',['../structproxsuite_1_1linalg_1_1veg_1_1cmp_1_1ref_1_1RefBase.html',1,'proxsuite::linalg::veg::cmp::ref']]],
  ['refmut_13',['RefMut',['../structproxsuite_1_1linalg_1_1veg_1_1RefMut.html',1,'proxsuite::linalg::veg']]],
  ['refmut_3c_20a_20_3e_14',['RefMut&lt; A &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1RefMut.html',1,'proxsuite::linalg::veg']]],
  ['refmut_3c_20c_20_3e_15',['RefMut&lt; C &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1RefMut.html',1,'proxsuite::linalg::veg']]],
  ['refmutbase_16',['RefMutBase',['../structproxsuite_1_1linalg_1_1veg_1_1cmp_1_1mut_1_1RefMutBase.html',1,'proxsuite::linalg::veg::cmp::mut']]],
  ['relocate_5fpointer_17',['relocate_pointer',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1__collections_1_1relocate__pointer.html',1,'proxsuite::linalg::veg::_detail::_collections::relocate_pointer&lt; T, bool &gt;'],['../structproxsuite_1_1linalg_1_1veg_1_1collections_1_1relocate__pointer.html',1,'proxsuite::linalg::veg::collections::relocate_pointer&lt; T &gt;']]],
  ['relocate_5fpointer_3c_20t_2c_20false_20_3e_18',['relocate_pointer&lt; T, false &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1__collections_1_1relocate__pointer_3_01T_00_01false_01_4.html',1,'proxsuite::linalg::veg::_detail::_collections']]],
  ['relocate_5fpointer_5ftrivial_19',['relocate_pointer_trivial',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1__collections_1_1relocate__pointer__trivial.html',1,'proxsuite::linalg::veg::_detail::_collections']]],
  ['relocfn_20',['RelocFn',['../structproxsuite_1_1linalg_1_1veg_1_1mem_1_1RelocFn.html',1,'proxsuite::linalg::veg::mem']]],
  ['results_21',['Results',['../structproxsuite_1_1proxqp_1_1Results.html',1,'proxsuite::proxqp']]],
  ['ret_5f_22',['Ret_',['../structproxsuite_1_1proxqp_1_1detail_1_1Ret__.html',1,'proxsuite::proxqp::detail']]],
  ['returns_5fvoid_5fimpl_23',['returns_void_impl',['../structtl_1_1detail_1_1returns__void__impl.html',1,'tl::detail']]],
  ['returns_5fvoid_5fimpl_3c_20f_2c_20void_5ft_3c_20invoke_5fresult_5ft_3c_20f_2c_20u_2e_2e_2e_20_3e_20_3e_2c_20u_2e_2e_2e_20_3e_24',['returns_void_impl&lt; F, void_t&lt; invoke_result_t&lt; F, U... &gt; &gt;, U... &gt;',['../structtl_1_1detail_1_1returns__void__impl_3_01F_00_01void__t_3_01invoke__result__t_3_01F_00_01U_d550cf27283c1c228efcceae556d7c6b.html',1,'tl::detail']]],
  ['rowcolaccessimpl_25',['RowColAccessImpl',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RowColAccessImpl.html',1,'proxsuite::linalg::dense::_detail']]],
  ['rowcolaccessimpl_3c_20false_20_3e_26',['RowColAccessImpl&lt; false &gt;',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RowColAccessImpl_3_01false_01_4.html',1,'proxsuite::linalg::dense::_detail']]],
  ['rowcolaccessimpl_3c_20true_20_3e_27',['RowColAccessImpl&lt; true &gt;',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1RowColAccessImpl_3_01true_01_4.html',1,'proxsuite::linalg::dense::_detail']]],
  ['ruizequilibration_28',['RuizEquilibration',['../structproxsuite_1_1proxqp_1_1dense_1_1preconditioner_1_1RuizEquilibration.html',1,'proxsuite::proxqp::dense::preconditioner::RuizEquilibration&lt; T &gt;'],['../structproxsuite_1_1proxqp_1_1sparse_1_1preconditioner_1_1RuizEquilibration.html',1,'proxsuite::proxqp::sparse::preconditioner::RuizEquilibration&lt; T, I &gt;']]]
];
