var searchData=
[
  ['settings_0',['Settings',['../structproxsuite_1_1proxqp_1_1Settings.html',1,'proxsuite::proxqp']]],
  ['setzeroimpl_1',['SetZeroImpl',['../structproxsuite_1_1proxqp_1_1detail_1_1SetZeroImpl.html',1,'proxsuite::proxqp::detail']]],
  ['setzeroimpl_3c_20t_2c_20true_20_3e_2',['SetZeroImpl&lt; T, true &gt;',['../structproxsuite_1_1proxqp_1_1detail_1_1SetZeroImpl_3_01T_00_01true_01_4.html',1,'proxsuite::proxqp::detail']]],
  ['sign_5fextend_3',['sign_extend',['../structproxsuite_1_1linalg_1_1sparse_1_1util_1_1nb_1_1sign__extend.html',1,'proxsuite::linalg::sparse::util::nb']]],
  ['simdalignedsystemalloc_4',['SimdAlignedSystemAlloc',['../structproxsuite_1_1linalg_1_1dense_1_1__detail_1_1SimdAlignedSystemAlloc.html',1,'proxsuite::linalg::dense::_detail']]],
  ['simpleituple_5',['SimpleITuple',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1SimpleITuple.html',1,'proxsuite::linalg::veg::_detail']]],
  ['simpleituple_3c_20_5fmeta_3a_3ainteger_5fsequence_3c_20usize_2c_20is_2e_2e_2e_20_3e_2c_20ts_2e_2e_2e_20_3e_6',['SimpleITuple&lt; _meta::integer_sequence&lt; usize, Is... &gt;, Ts... &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1SimpleITuple_3_01__meta_1_1integer__sequence_3_03280e6cc7eeb52352ef307fb2696e6bf.html',1,'proxsuite::linalg::veg::_detail']]],
  ['simpleituple_3c_20_5fmeta_3a_3amake_5findex_5fsequence_3c_20sizeof_2e_2e_2e_28ts_29_3e_2c_20ts_2e_2e_2e_20_3e_7',['SimpleITuple&lt; _meta::make_index_sequence&lt; sizeof...(Ts)&gt;, Ts... &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1SimpleITuple.html',1,'proxsuite::linalg::veg::_detail']]],
  ['simpleleaf_8',['SimpleLeaf',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1SimpleLeaf.html',1,'proxsuite::linalg::veg::_detail']]],
  ['simpleleaf_3c_20is_2c_20ts_20_3e_9',['SimpleLeaf&lt; Is, Ts &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1SimpleLeaf.html',1,'proxsuite::linalg::veg::_detail']]],
  ['slice_10',['Slice',['../structproxsuite_1_1linalg_1_1sparse_1_1Slice.html',1,'proxsuite::linalg::sparse::Slice&lt; T &gt;'],['../structproxsuite_1_1linalg_1_1veg_1_1Slice.html',1,'proxsuite::linalg::veg::Slice&lt; T &gt;']]],
  ['slice_3c_20bool_20_3e_11',['Slice&lt; bool &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1Slice.html',1,'proxsuite::linalg::veg']]],
  ['slicemut_12',['SliceMut',['../structproxsuite_1_1linalg_1_1sparse_1_1SliceMut.html',1,'proxsuite::linalg::sparse::SliceMut&lt; T &gt;'],['../structproxsuite_1_1linalg_1_1veg_1_1SliceMut.html',1,'proxsuite::linalg::veg::SliceMut&lt; T &gt;']]],
  ['sparsemodel_13',['SparseModel',['../structproxsuite_1_1proxqp_1_1sparse_1_1SparseModel.html',1,'proxsuite::proxqp::sparse']]],
  ['specialize_5flen_14',['specialize_len',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1__meta_1_1specialize__len.html',1,'proxsuite::linalg::veg::_detail::_meta']]],
  ['specialize_5flen_3c_20f_2c_20f_3c_20ts_2e_2e_2e_20_3e_20_3e_15',['specialize_len&lt; F, F&lt; Ts... &gt; &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1__meta_1_1specialize__len_3_01F_00_01F_3_01Ts_8_8_8_01_4_01_4.html',1,'proxsuite::linalg::veg::_detail::_meta']]],
  ['specializes_16',['specializes',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1__meta_1_1specializes.html',1,'proxsuite::linalg::veg::_detail::_meta']]],
  ['specializes_3c_20f_2c_20f_3c_20ts_2e_2e_2e_20_3e_20_3e_17',['specializes&lt; F, F&lt; Ts... &gt; &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1__detail_1_1__meta_1_1specializes_3_01F_00_01F_3_01Ts_8_8_8_01_4_01_4.html',1,'proxsuite::linalg::veg::_detail::_meta']]],
  ['sqrt_18',['sqrt',['../structproxsuite_1_1proxqp_1_1dense_1_1nb_1_1sqrt.html',1,'proxsuite::proxqp::dense::nb']]],
  ['stackalloc_19',['StackAlloc',['../structproxsuite_1_1linalg_1_1veg_1_1mem_1_1StackAlloc.html',1,'proxsuite::linalg::veg::mem']]],
  ['stackreq_20',['StackReq',['../structproxsuite_1_1linalg_1_1veg_1_1dynstack_1_1StackReq.html',1,'proxsuite::linalg::veg::dynstack']]],
  ['static_5fconst_21',['static_const',['../structproxsuite_1_1linalg_1_1veg_1_1meta_1_1static__const.html',1,'proxsuite::linalg::veg::meta']]],
  ['str_22',['Str',['../structproxsuite_1_1linalg_1_1veg_1_1Str.html',1,'proxsuite::linalg::veg']]],
  ['stridedvectorview_23',['StridedVectorView',['../structproxsuite_1_1proxqp_1_1StridedVectorView.html',1,'proxsuite::proxqp']]],
  ['stridedvectorviewmut_24',['StridedVectorViewMut',['../structproxsuite_1_1proxqp_1_1StridedVectorViewMut.html',1,'proxsuite::proxqp']]],
  ['strliteralconstant_25',['StrLiteralConstant',['../structproxsuite_1_1linalg_1_1veg_1_1StrLiteralConstant.html',1,'proxsuite::linalg::veg']]],
  ['strliteralconstant_3c_20charunit_28literaltype_3a_3avalue_28_29_5bis_5d_29_2e_2e_2e_20_3e_26',['StrLiteralConstant&lt; CharUnit(LiteralType::value()[Is])... &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1StrLiteralConstant.html',1,'proxsuite::linalg::veg']]],
  ['strliteralconstant_3c_20charunit_28literaltype_3a_3avalue_5bis_5d_29_2e_2e_2e_20_3e_27',['StrLiteralConstant&lt; CharUnit(LiteralType::value[Is])... &gt;',['../structproxsuite_1_1linalg_1_1veg_1_1StrLiteralConstant.html',1,'proxsuite::linalg::veg']]],
  ['symbolicmatmut_28',['SymbolicMatMut',['../structproxsuite_1_1linalg_1_1sparse_1_1SymbolicMatMut.html',1,'proxsuite::linalg::sparse']]],
  ['symbolicmatmutinterface_29',['SymbolicMatMutInterface',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatMutInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatmutinterface_3c_20matmut_3c_20t_2c_20i_20_3e_2c_20i_20_3e_30',['SymbolicMatMutInterface&lt; MatMut&lt; T, I &gt;, I &gt;',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatMutInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatmutinterface_3c_20matmut_3c_20t_2c_20isize_20_3e_2c_20isize_20_3e_31',['SymbolicMatMutInterface&lt; MatMut&lt; T, isize &gt;, isize &gt;',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatMutInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatmutinterface_3c_20symbolicmatmut_3c_20isize_20_3e_2c_20isize_20_3e_32',['SymbolicMatMutInterface&lt; SymbolicMatMut&lt; isize &gt;, isize &gt;',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatMutInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatref_33',['SymbolicMatRef',['../structproxsuite_1_1linalg_1_1sparse_1_1SymbolicMatRef.html',1,'proxsuite::linalg::sparse']]],
  ['symbolicmatrefinterface_34',['SymbolicMatRefInterface',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatRefInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatrefinterface_3c_20matmut_3c_20t_2c_20i_20_3e_2c_20i_20_3e_35',['SymbolicMatRefInterface&lt; MatMut&lt; T, I &gt;, I &gt;',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatRefInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatrefinterface_3c_20matmut_3c_20t_2c_20isize_20_3e_2c_20isize_20_3e_36',['SymbolicMatRefInterface&lt; MatMut&lt; T, isize &gt;, isize &gt;',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatRefInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatrefinterface_3c_20matref_3c_20t_2c_20i_20_3e_2c_20i_20_3e_37',['SymbolicMatRefInterface&lt; MatRef&lt; T, I &gt;, I &gt;',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatRefInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatrefinterface_3c_20matref_3c_20t_2c_20isize_20_3e_2c_20isize_20_3e_38',['SymbolicMatRefInterface&lt; MatRef&lt; T, isize &gt;, isize &gt;',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatRefInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatrefinterface_3c_20symbolicmatmut_3c_20isize_20_3e_2c_20isize_20_3e_39',['SymbolicMatRefInterface&lt; SymbolicMatMut&lt; isize &gt;, isize &gt;',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatRefInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['symbolicmatrefinterface_3c_20symbolicmatref_3c_20isize_20_3e_2c_20isize_20_3e_40',['SymbolicMatRefInterface&lt; SymbolicMatRef&lt; isize &gt;, isize &gt;',['../structproxsuite_1_1linalg_1_1sparse_1_1__detail_1_1SymbolicMatRefInterface.html',1,'proxsuite::linalg::sparse::_detail']]],
  ['systemalloc_41',['SystemAlloc',['../structproxsuite_1_1linalg_1_1veg_1_1mem_1_1SystemAlloc.html',1,'proxsuite::linalg::veg::mem']]]
];
