name: CI - ArchLinux

on:
  push:
    branches:
      - devel
  pull_request:
    paths-ignore:
      - CHANGELOG.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-with-arch:
    name: CI - ArchLinux
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:
      - run: pacman -Syu --noconfirm cmake ninja catch2 git eigen cereal libmatio doxygen graphviz nanobind python-scipy simde
      - uses: actions/checkout@v7
      - run: cmake -G Ninja -B build -S . -DBUILD_PYTHON_INTERFACE=ON
      - run: cmake --build build
      - run: ctest --test-dir build --output-on-failure
