name: CI - Linux/OSX/Windows - Conda

on:
  push:
    branches:
      - devel
  pull_request:
    paths-ignore:
      - CHANGELOG.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-with-conda:
    name: '[conda:${{ matrix.os }}:${{ matrix.build_type }}:c++${{ matrix.cxx_std }}]'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        name: [ubuntu-latest, macos-latest, windows-2022-clang-cl, windows-2022, macos-15-intel]
        cxx_std: [17, 20]
        continue_on_error: [false]

        include:
          - name: ubuntu-latest
            os: ubuntu-latest
          - name: macos-latest
            os: macos-latest
          - name: macos-15-intel
            os: macos-15-intel
          - name: windows-2022-clang-cl
            os: windows-2022
            compiler: clang-cl
          - name: windows-2022
            os: windows-2022
            compiler: cl
          - name: macos-latest
            os: macos-latest
            build_type: Debug
            cxx_std: 17
            continue_on_error: true
          - name: macos-latest
            os: macos-latest
            build_type: Debug
            cxx_std: 20
            continue_on_error: true

        exclude:
          - name: macos-latest
            build_type: Debug
            cxx_std: 17
            continue_on_error: false
          - name: macos-latest
            build_type: Debug
            cxx_std: 20
            continue_on_error: false

    steps:
    - uses: actions/checkout@v7

    - uses: conda-incubator/setup-miniconda@v4
      with:
        activate-environment: proxsuite
        environment-file: .github/workflows/conda/environment.yml
        auto-activate-base: false
        auto-update-conda: true

    - name: Install dependencies [Conda/Windows-2022]
      if: contains(matrix.os, 'windows-2022')
      shell: bash -l {0}
      run: |
        # Use VS2022 on Windows-2022
        conda install vs2022_win-64

    - name: Activate ccache [Conda]
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.cxx_std }}
        max-size: 1G

    - name: Print environment [Conda]
      run: |
        conda info
        conda list
        env

    - name: Configure [Conda/Linux&macOS]
      if: contains(matrix.os, 'macos-') || contains(matrix.os, 'ubuntu')
      run: |
        cmake -B build -S . -GNinja \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DCMAKE_INSTALL_PREFIX="${CONDA_PREFIX}" \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_CXX_STANDARD=${{ matrix.cxx_std }} \
          -DBUILD_PYTHON_INTERFACE=ON \
          -DBUILD_DOCUMENTATION=ON \
          -DINSTALL_DOCUMENTATION=ON \
          -DBUILD_WITH_VECTORIZATION_SUPPORT=ON

    - name: Configure [Conda/Windows]
      if: contains(matrix.os, 'windows-')
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.compiler }}
      run: |
        cmake -B build -S . -GNinja ^
          -DCMAKE_C_COMPILER_LAUNCHER=ccache ^
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ^
          -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%/Library ^
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
          -DCMAKE_CXX_STANDARD=${{ matrix.cxx_std }} ^
          -DBUILD_PYTHON_INTERFACE=ON ^
          -DBUILD_WITH_OPENMP_SUPPORT=ON ^
          -DLINK_PYTHON_INTERFACE_TO_OPENMP=ON ^
          -DBUILD_DOCUMENTATION=ON ^
          -DINSTALL_DOCUMENTATION=ON ^
          -DBUILD_WITH_VECTORIZATION_SUPPORT=ON

    - name: Build [Conda/Linux&macOS]
      if: contains(matrix.os, 'macos-') || contains(matrix.os, 'ubuntu')
      run: |
        cmake --build build --config ${{ matrix.build_type }} -v -j 1

    - name: Build [Conda/Windows]
      if: contains(matrix.os, 'windows-')
      run: |
        cmake --build build --config ${{ matrix.build_type }} -v -j 1

    - name: Build documentation [Conda]
      run: |
        cmake --build build --config ${{ matrix.build_type }} --target doc

    - name: Install [Conda]
      run: |
        cmake --install build --config ${{ matrix.build_type }}

    - name: Test [Conda]
      continue-on-error: ${{ matrix.continue_on_error }}
      run: |
        ctest --test-dir build --output-on-failure -C ${{ matrix.build_type }}

    - name: Test FetchContent packaging [Conda/Linux&macOS]
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      run: |
        export PROXSUITE_GIT_REPOSITORY="file://"$GITHUB_WORKSPACE
        export PROXSUITE_GIT_TAG="test-external-"$(git rev-parse --short HEAD)
        git tag $PROXSUITE_GIT_TAG
        cmake -B build/test-packaging-external -S test/packaging/external -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build build/test-packaging-external --config ${{ matrix.build_type }}

    - name: Test CMake packaging [Conda/Linux&macOS]
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      run: |
        cmake -B build/test-packaging-cmake -S test/packaging/cmake -DCMAKE_INSTALL_PREFIX="${CONDA_PREFIX}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build build/test-packaging-cmake --config ${{ matrix.build_type }}

    - name: Test CMake packaging with components [Conda/Linux&macOS]
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      run: |
        cmake -B build/test-packaging-cmake-components -S test/packaging/cmake-components -DCMAKE_INSTALL_PREFIX="${CONDA_PREFIX}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_WITH_VECTORIZATION_SUPPORT=ON
        cmake --build build/test-packaging-cmake-components --config ${{ matrix.build_type }}

    - name: Uninstall [Conda]
      run: |
        cmake --build build --config ${{ matrix.build_type }} --target uninstall

    - name: Display ccache statistics [Conda]
      run: |
        echo $(ccache -s)

  check:
    if: always()
    name: check-ci-linux-osx-win-conda

    needs:
    - build-with-conda

    runs-on: Ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
