name: PyPI Wheel

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Only cancel workflow on new push if we are not releasing
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  wheel:
    name: "Wheel - ${{ matrix.os }} - Python ${{ matrix.pixi_environment }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        pixi_environment: [py310, py311, py312, py313, py314]
        os: [ubuntu-24.04, macos-15-intel, macos-26, windows-2025]
    steps:
      - uses: actions/checkout@v6

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: ${{ matrix.pixi_environment }}

      - name: Build, check, and test wheel
        run: pixi run -e ${{ matrix.pixi_environment }} test-wheel

      - name: Archive artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-${{ matrix.os }}-${{ matrix.pixi_environment }}
          path: dist/*.whl

  release:
    needs: wheel
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        pixi_environment: [py310, py311, py312, py313, py314]
        os: [ubuntu-24.04, macos-15-intel, macos-26, windows-2025]
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: dist-${{ matrix.os }}-${{ matrix.pixi_environment }}
          merge-multiple: true
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.13
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true

  check:
    if: always()
    name: check-release

    needs:
    - wheel
    - release

    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
