name: CI - Pixi - Windows/Linux/macOS

on:
  push:
    branches:
      - devel
  pull_request:
    paths-ignore:
      - CHANGELOG.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pixi-ci:
    name: Pixi CI - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 6
      # Since pixi will install a compiler, the compiler mtime will be changed.
      # This can invalidate the cache (https://ccache.dev/manual/latest.html#config_compiler_check)
      CCACHE_COMPILERCHECK: content
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 22.04
            os: ubuntu-22.04

          - name: Ubuntu 24.04
            os: ubuntu-24.04

          - name: macOS x86_64 (Intel)
            os: macos-15-intel

          - name: macOS ARM64 (Apple Silicon)
            os: macos-26

          - name: Windows Server 2022
            os: windows-2022

          - name: Windows Server 2025
            os: windows-2025

    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-pixi-${{ matrix.os }}-${{ github.sha }}
          restore-keys: ccache-pixi-${{ matrix.os }}-

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: latest

      - name: Install Pixi environment
        run: pixi install

      - name: Configure project
        run: pixi run configure

      - name: Build project
        run: pixi run build

      - name: Run tests
        run: pixi run test

      - name: Run test packaging
        run: pixi run test-packaging
