name: CI - ROS - Linux
on:
  push:
    branches:
      - devel
  pull_request:
    paths-ignore:
      - CHANGELOG.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ros:
    name: ROS ${{ matrix.ROS_DISTRO }} - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # ROS2 Humble Hawksbill (May 2022 - May 2027)
          - ROS_DISTRO: humble
            os: Ubuntu 22.04 (Jammy)

          # ROS2 Jazzy Jalisco (May 2024 - May 2029)
          - ROS_DISTRO: jazzy
            os: Ubuntu 24.04 (Noble)

          # ROS2 Kilted Kayu (May 2025 - December 2026)
          - ROS_DISTRO: kilted
            os: Ubuntu 24.04 (Noble)

          # ROS2 Rolling Ridley
          - ROS_DISTRO: rolling
            os: Ubuntu 26.04 (Resolute)

          # ROS2 Lyrical Luth (May 2026 - May 2031)
          - ROS_DISTRO: lyrical
            os: Ubuntu 26.04 (Resolute)
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-ci-ros-${{ matrix.ROS_DISTRO }}-${{github.run_id}}
          restore-keys: ccache-ci-ros-${{ matrix.ROS_DISTRO }}-
      - uses: ros-industrial/industrial_ci@125164b9f1883cdf1858897a7146d1bebf2be5c6
        env:
          CMAKE_ARGS: -DBUILD_WITH_VECTORIZATION_SUPPORT=ON -DPROXSUITE_BUILD_WITH_SERIALIZATION=ON -DBUILD_PYTHON_INTERFACE=ON -DBUILD_TESTING=ON -DPROXSUITE_BUILD_EXAMPLES=ON -DBUILD_BENCHMARK=ON
          VERBOSE_OUTPUT: true
          VERBOSE_TESTS: true
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}

  check:
    if: always()
    name: check-ci-linux-ros

    needs:
    - ros

    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
