name: Github Pages Deployment
on:
  release:
    types:
      - published

jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          environments: doc

      - name: Build documentation
        run: pixi run -e doc build_documentation

      - name: Install documentation
        run: pixi run -e doc install_documentation

      - name: Archive artifacts
        uses: actions/upload-artifact@v7
        with:
          name: site
          path: build/doc/html

  deploy:
    runs-on: ubuntu-latest
    needs: [build_doc]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: site
          path: site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          folder: site
